test: FORCE
	cd test && testexotimo

SPECSOURCE_DIR = ./src
specsources: FORCE
	rm -rf $(SPECSOURCE_DIR)
	./util/devel/src/extract_sources -o $(SPECSOURCE_DIR) spec/*.tex

SPECTEST_DIR = ./test
spectests: FORCE
	rm -rf $(SPECTEST_DIR)
	./util/devel/test/extract_tests -o $(SPECTEST_DIR) spec/*.tex
FORCE:
